### ISSUE TITLE
Buttons On toss.html

### ISSUE THREAD

**Issue by E13ctron** [E13ctron/Odd-or-even-web#2]
Styling buttons of toss.html to beautify the page

**Comment by krishnasinghdev** [comment]
Will you give me chance to do this .

**Comment by E13ctron** [comment]
@GODFATHER0054  yes go ahead

**Comment by E13ctron** [comment]
@GODFATHER0054  if you want a more clean file you could create a new css file and link it

**Comment by krishnasinghdev** [comment]
> @GODFATHER0054  if you want a more clean file you could create a new css file and link it 

Thanks for giving me the opportunity
